language: node_js

node_js:
- '8'

branches:
  only:
  - master
  - /^greenkeeper/.*$/

install:
- npm install

notifications:
  email:
    recipients:
    - liuderchi@gmail.com
    on_success: never
    on_failure: change

script: npm run validation
